export interface FilterModel {
    booleanFilter: BooleanFilter,
    categoryFilter: CategoryFilter
}
export interface BooleanFilter {
    atmosphere_romantic: boolean,
    atmosphere_cozy: boolean,
    atmosphere_view: boolean,
    atmosphere_hot_spot: boolean,
    atmosphere_dressy: boolean,
    atmosphere_upscale: boolean,
    atmosphere_casual: boolean,
    diet_healthy: boolean,
    diet_vegetarian_friendly: boolean,
    diet_vegan_options: boolean,
    diet_gluten_free_options: boolean,
    diet_halal: boolean, diet_kosher: boolean,
    diet_keto: boolean, diet_pescatarian: boolean,
    entertain_full_bar: boolean,
    entertain_beer_wine: boolean,
    entertain_happy_hour: boolean,
    entertain_music: boolean,
    entertain_live_music: boolean,
    entertain_dancing: boolean,
    entertain_karaoke: boolean,
    type_restaurant: boolean,
    type_bakery: boolean,
    type_bars_nightlife: boolean,
    type_coffee_tea: boolean,
    type_dessert: boolean,
    type_specialty_food: boolean,
    general_no_smoking: boolean,
    general_parking_available: boolean,
    general_wheelchair_accessible: boolean,
    general_outdoor_seating: boolean,
    general_dog_friendly: boolean,
    good_kids: boolean,
    good_groups: boolean,
    good_dining_solo: boolean,
    good_working: boolean,
    meals_breakfast: boolean,
    meals_brunch: boolean,
    meals_lunch: boolean,
    meals_dinner: boolean,
    meals_quick_bites: boolean,
    meals_dessert: boolean,
    meals_late_night: boolean,
    payment_credit_cards: boolean,
    payment_discover: boolean,
    payment_mastercard: boolean,
    payment_visa: boolean,
    payment_amex: boolean,
    payment_cash_only: boolean,
    payment_digital: boolean
}
export interface CategoryFilter {
    propono_primary_category: Category
    propono_sub_categories: Category
}
export enum Category {
    Bar = 'Bar',
    Breakfast = 'Breakfast',
    Brunch = 'Brunch',
    Cider_Bar = 'Cider Bar',
    Cocktail_Bar = 'Cocktail Bar',
    American = 'American',
    Beer_Garden = 'Beer Garden',
    Beer_Hall = 'Beer Hall',
    Cabaret_Club = 'Cabaret Club',
    Champagne_Bars = 'Champagne Bars',
    Chocolate = 'Chocolate',
    Churros = 'Churros',
    Cigar_Bar = 'Cigar Bar',
    Country_Dance = 'Country Dance',
    Hall = 'Hall',
    Dance_Club = 'Dance Club',
    Dart_Bar = 'Dart Bar',
    Desserts = 'Desserts',
    Disco_Club = 'Disco Club',
    Distillery = 'Distillery',
    Dive_Bar = 'Dive Bar',
    Fast_Food = 'Fast Food',
    Fine_Dining = 'Fine Dining',
    Gay_Bar = 'Gay Bar',
    Gay_Night_Club = 'Gay Night Club'
}